---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <API_TOKEN>

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-new-prod
spec:
  acme:
    email: alex@jmetio.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          email: alex.nguepi@web.de
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-prod
  namespace: dev
spec:
  secretName: cert-prod-tls
  issuerRef:
    name: letsencrypt-new-prod
    kind: ClusterIssuer
  commonName: "*.prod.monlabo.de"
  dnsNames:
  - "prod.monlabo.de"
  - "*.prod.monlabo.de"



