apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-sock-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/f3lin/test-argocd.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-eks.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true